# Prefix Configuration
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Terminal & Colors, match window background to Kitty
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-kitty:RGB"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

# Clipboard & Mouse
set -g mouse on
set-option -g set-clipboard on   # Use system clipboard automatically
setw -g mode-keys vi

# Selection with 'v' and yank with 'y'
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Pane Resizing (Shift + H/J/K/L)
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Status Bar (Catppuccin look)
set -g status-position bottom
set -g @catppuccin_window_status_enable "yes"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}" 

# TPM Initialization
run '~/.tmux/plugins/tpm/tpm'

# Color Overrides to match kitty colors
set -g status-style "bg=#1a1b26,fg=#c0caf5"
set -g window-style "bg=#1a1b26"
set -g window-active-style "bg=#1a1b26"
