# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        13.0
adjust_line_height  110%
adjust_column_width  100%

# Cursor
cursor_shape      block
cursor_blink      on
cursor_stop_blinking_after 5.0

# Window Layout
window_padding_width  8
window_margin_width   0
confirm_os_window_close 0

# Performance
repaint_delay         7
input_delay           1
sync_to_monitor       yes
max_frame_rate        165
allow_remote_control  yes

# Scroll
scrollback_lines 50000
wheel_scroll_multiplier 3.0

# Copy & Paste
copy_on_select yes
strip_trailing_spaces never

# Mouse
mouse_hide_wait 3.0

# Colors (TokyoNight Storm)
foreground            #c0caf5
background            #1a1b26
selection_background  #33467C
selection_foreground  #c0caf5
cursor                #c0caf5

color0   #15161e
color1   #f7768e
color2   #9ece6a
color3   #e0af68
color4   #7aa2f7
color5   #bb9af7
color6   #7dcfff
color7   #a9b1d6

color8   #414868
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7aa2f7
color13  #bb9af7
color14  #7dcfff
color15  #c0caf5

# Keybindings
map ctrl+shift+enter    no_op
map ctrl+alt+enter      no_op
map ctrl+shift+t        no_op
map ctrl+shift+q        no_op
map ctrl+shift+right    no_op
map ctrl+shift+left     no_op

# Font Size
map ctrl+shift+equal increase_font_size
map ctrl+shift+minus decrease_font_size
map ctrl+shift+backspace restore_font_size

# Misc
open_url_with default
startup_session none
enable_audio_bell no

